id: shutters_open_sunrise_close_sunset
alias: Shutters - Open Sunrise / Close Sunset
description: ""
triggers:
  - trigger: sun
    event: sunrise
    offset: -00:10:00
    id: sunrise_offset
  - trigger: sun
    event: sunset
    offset: 00:10:00
    id: sunset_offset
  - trigger: homeassistant
    event: start
    id: ha_start
  - trigger: time_pattern
    minutes: /15
    id: periodic
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: ha_start
        sequence:
          - delay: 00:00:05
  - choose:
      - conditions:
          - condition: trigger
            id: sunrise_offset
        sequence:
          - action: cover.set_cover_position
            target:
              entity_id: "{{ members }}"
            data:
              position: 100
      - conditions:
          - condition: trigger
            id: sunset_offset
        sequence:
          - action: cover.set_cover_position
            target:
              entity_id: "{{ members }}"
            data:
              position: 0
      - conditions:
          - condition: template
            value_template: "{{ should_be_open }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ eligible_members | length > 0 }}"
                sequence:
                  - action: cover.set_cover_position
                    target:
                      entity_id: "{{ eligible_members }}"
                    data:
                      position: 100
    default:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ eligible_members | length > 0 }}"
            sequence:
              - action: cover.set_cover_position
                target:
                  entity_id: "{{ eligible_members }}"
                data:
                  position: 0
variables:
  open_offset_s: -600
  close_offset_s: 600
  now_ts: "{{ as_timestamp(utcnow()) | float }}"
  next_rising_ts: "{{ as_timestamp(state_attr('sun.sun','next_rising')) | float
    }}"
  next_setting_ts: "{{ as_timestamp(state_attr('sun.sun','next_setting')) |
    float }}"
  sunrise_day_ts:
    "{% if is_state('sun.sun','above_horizon') %}\n  {{ next_rising_ts
    - 86400 }}\n{% else %}\n  {{ next_rising_ts }}\n{% endif %}"
  sunset_day_ts: "{% if now_ts < next_setting_ts %}\n  {{ next_setting_ts }}\n{%
    else %}\n  {{ next_setting_ts - 86400 }}\n{% endif %}"
  open_ts: "{{ sunrise_day_ts + open_offset_s }}"
  close_ts: "{{ sunset_day_ts + close_offset_s }}"
  should_be_open: "{{ open_ts <= now_ts < close_ts }}"
  members: "{{ expand('cover.shutters') | map(attribute='entity_id') | list
    }}"
  boundary_ts:
    "{% if should_be_open %}\n  {{ open_ts }}\n{% else %}\n  {{ close_ts
    }}\n{% endif %}"
  eligible_members:
    "{% set ns = namespace(out=[]) %} {% for s in expand('cover.shutters')
    %}\n  {% set was_manual = (s.context.user_id is not none) %}\n  {% set changed_ts
    = as_timestamp(s.last_changed) | float %}\n  {% if not (was_manual and changed_ts
    > boundary_ts) %}\n    {% set ns.out = ns.out + [s.entity_id] %}\n  {% endif
    %}\n{% endfor %} {{ ns.out }}"
mode: single
